services:
  tac1-boost:
    build:
      context: .
      args:
        - GOOGLE_CLIENT_ID=${GOOGLE_CLIENT_ID}
        - GOOGLE_CLIENT_SECRET=${GOOGLE_CLIENT_SECRET}
        - AUTH_SECRET=${AUTH_SECRET}
    ports:
      - '3500:3500'
    env_file:
      - .env
    environment:
      - NODE_ENV=production
    restart: unless-stopped
